# Generated by Django 4.0.4 on 2022-06-22 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados_cliente', models.CharField(max_length=100)),
                ('dados_corretor', models.CharField(max_length=100)),
                ('descricao_imovel', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=100)),
                ('documentacao', models.CharField(max_length=100)),
                ('clausula_penal', models.CharField(max_length=100)),
            ],
        ),
    ]
