# Generated by Django 4.0.4 on 2022-06-22 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financeira', models.CharField(max_length=100)),
                ('nome_cliente', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=100)),
                ('data_abertura', models.CharField(max_length=100)),
            ],
        ),
    ]
